#
# examples: https://github.com/itzg/docker-minecraft-server/tree/master/examples
#
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      DIFFICULTY: "hard"
      MEMORY: "2G"
      MAX_PLAYERS: "2"
      SERVER_NAME: "phills&wills"
      WORLD_SIZE: "20000"

      TYPE: FABRIC
      VERSION: "1.20.4"
      # journeymap: https://teamjm.github.io/journeymap-docs/latest/Server%20Docs/Commands/waypoint_command/
      MODRINTH_PROJECTS: |
        fabric-api
        lithium
        fallingtree
        journeymap
        zombie-horse-spawn
        skeleton-horse-spawn
        when-dungeons-arise-seven-seas
        yungs-better-dungeons
        yungs-better-mineshafts
        yungs-better-nether-fortresses
        yungs-better-ocean-monuments
        yungs-better-strongholds
        yungs-better-witch-huts
        yungs-better-end-island
        yungs-better-jungle-temples
        yungs-better-desert-temples
        yungs-bridges
        dungeons-and-taverns
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      # MODRINTH_ALLOWED_VERSION_TYPE: "release"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data

volumes:
  data: {}
